### ISSUE TITLE
How to change the TV speaker preset through the app?

### ISSUE THREAD

**Issue by Amoeba00** [Maassoft/ColorControl#66]
C1 is plagued by a bug where the speakers always default to GAME OPTIMIZER sound preset (that is garbage) if you have gsync enabled.

_Originally posted by @epsilon-a in https://github.com/Maassoft/ColorControl/issues/53#issuecomment-1002774512_

**Comment by Amoeba00** [comment]
Currently, the quickest way with the remote is to add the sound button on the quick access panel on the left side, but you still need the remote.
What are the steps involved to automate switching Game Optimizer sound to another one like AI Sound Pro?

**Comment by epsilon-a** [comment]
> Currently, the quickest way with the remote is to add the sound button on the quick access panel on the left side, but you still need the remote. What are the steps involved to automate switching Game Optimizer sound to another one like AI Sound Pro?

It would be easy to automate the switching, but I don't know what is the toggle for the quick access settings inside the app. Doing it from the regular settings is much slower

**Comment by Amoeba00** [comment]
Agreed.  Is there a button or link within the app to have the quick access menu pop up?

**Comment by Maassoft** [comment]
There's no button yet, but there's an app called "Magic Number" on my C9 which opens the Quick Access menu.
About changing the "sound mode" or "sound output": that's currently not possible through the app, but I think it's possible to add it.

**Comment by Amoeba00** [comment]
On the C1 remote - there's a sprocket/wheel (similar to the one on the app's remote picture) - long press gets you the all settings - one press gets you the quick access menu (with editable buttons).
I'm trying to figure out how to add a proper sequence with the app and not having any success.
What am I missing here?  How would this look in the app?

Here's the sequence from the remote:
All Settings
down (gets you to sound section)
right (gets you to the sound settings)
enter (first setting is sound mode)
up 6 (game optimizer is at the bottom - AI Sound Pro is at the top)
enter (selects the sound mode)
exit (exits the menu)

Thanks!

**Comment by epsilon-a** [comment]
> On the C1 remote - there's a sprocket/wheel (similar to the one on the app's remote picture) - long press gets you the all settings - one press gets you the quick access menu (with editable buttons). I'm trying to figure out how to add a proper sequence with the app and not having any success. What am I missing here? How would this look in the app?
> 
> Here's the sequence from the remote: All Settings down (gets you to sound section) right (gets you to the sound settings) enter (first setting is sound mode) up 6 (game optimizer is at the bottom - AI Sound Pro is at the top) enter (selects the sound mode) exit (exits the menu)
> 
> Thanks!

App: Settings

BLUE:1000, DOWN:500, RIGHT:500, ENTER:1000, DOWN:500, DOWN:500, ENTER:500, EXIT

**Comment by Amoeba00** [comment]
Corrected as follows:
BLUE:1000, DOWN:500, RIGHT:500, ENTER:1000, UP:500, UP:500, UP:500, UP:500, UP:500, UP:500, ENTER:500, EXIT

OK - that's close - but I guess that only works if the sound is on Game Optimizer - if not, then it shoots up to the help icon and launches that instead.
I wish there were a way to just set the sound mode directly - otherwise - the sequence all depends on the current setting.
Thanks for that code set though - at least it gets me to launching the All Settings menu.

**Comment by epsilon-a** [comment]
This thread was about game optimizer default, and that sequence changes it to Cinema which is the best preset.

So I don't know what you mean by corrected.

**Comment by Amoeba00** [comment]
> This thread was about game optimizer default, and that sequence changes it to Cinema which is the best preset.
> 
> So I don't know what you mean by corrected.

Ahh - my example/question was changing it from Game Optimizer to AI Sound Pro - I didn't know Cinema was the best preset.
But still,  if there were a way have a sequence so you could set whatever sound or any setting would be better - since it didn't matter what the current setting was.  Though I get it sounds easier than it is to actually implement.

**Comment by Maassoft** [comment]
I've just released 5.4.0.0 which now supports changing sound mode and sound output. Let me know if it works.

**Comment by Amoeba00** [comment]
OK - but it's still not clear how to trigger it.  Is there a set of instructions on how to build these custom steps?

For example - I'm guessing the App is Settings, but it's not clear what the steps are and just selection the action "soundMode (aiSoundPlus)" just brings up the regular settings menu.  Thanks!


![image](https://user-images.githubusercontent.com/39176113/152820507-45d20374-ec2c-419e-8720-55a8fa0d7026.png)

**Comment by epsilon-a** [comment]
> OK - but it's still not clear how to trigger it. Is there a set of instructions on how to build these custom steps?
> 
> For example - I'm guessing the App is Settings, but it's not clear what the steps are and just selection the action "soundMode (aiSoundPlus)" just brings up the regular settings menu. Thanks!
> 
> ![image](https://user-images.githubusercontent.com/39176113/152820507-45d20374-ec2c-419e-8720-55a8fa0d7026.png)

![image](https://user-images.githubusercontent.com/40537999/152846599-de24cb58-5946-4f42-b885-72ef48321ce8.png)

**Comment by Amoeba00** [comment]
Am I missing something? Nothing happens because there is no App selected. 
I even duplicated your example.

![image](https://user-images.githubusercontent.com/39176113/153082659-dab918cb-2aef-44eb-a9fb-58561157b515.png)

Thanks!

**Comment by epsilon-a** [comment]
It doesn't need an app...

You won't see anything happen unless you open sound menu.

**Comment by Amoeba00** [comment]
For those looking how to do this - here is my shortcut using CTRL-SHIFT-S as the shortcut.

![image](https://user-images.githubusercontent.com/39176113/160139129-ece8ec5f-1a95-4bee-9b72-b6c772cf3a4c.png)
